konstantins-buts/jg-java-1-online-winter-january-wednesday-2021

src/main/java/instructor/HelloWorld.java, src/main/java/students/julija_katukova/lesson_2/level_1/task_1/Task1.java
=> Task1 Attempt1

src/main/java/students/kristine/paskevica/lesson_2/level_1/task_1/Task1.java
=> 2. nodarbības, 1 līmeņa - 1. uzd, četras matemātiskās darbības ar veseliem skaitliem

src/main/java/students/rodion_afanasjev/lesson_3/level_2/task_8/Concatenation.java
=> Lesson-3-level-2-task-8

src/main/java/students/rodion_afanasjev/lesson_3/level_2/task_9/Console.java
=> Lesson-3-level-2-task-9

src/main/java/students/rodion_afanasjev/lesson_3/level_3/task_11/Robot.java, src/main/java/students/rodion_afanasjev/lesson_3/level_3/task_11/RobotDemo.java
=> St rodion afanasjev lesson 3 level 3 task 11

src/main/java/students/rodion_afanasjev/lesson_3/level_3/task_11/Robot.java, src/main/java/students/rodion_afanasjev/lesson_3/level_3/task_11/RobotDemo.java, src/main/java/students/rodion_afanasjev/lesson_3/level_4/task_14/Book.java, src/main/java/students/rodion_afanasjev/lesson_3/level_4/task_14/BookDemo.java, src/main/java/students/rodion_afanasjev/lesson_3/level_4/task_15/Phone.java, src/main/java/students/rodion_afanasjev/lesson_3/level_4/task_15/PhoneDemo.java, src/main/java/students/rodion_afanasjev/lesson_3/level_4/task_16/Car.java, src/main/java/students/rodion_afanasjev/lesson_3/level_4/task_16/CarDemo.java
=> St rodion afanasjev lesson 3 level 4

src/main/java/students/rodion_afanasjev/lesson_3/level_3/task_11/Robot.java, src/main/java/students/rodion_afanasjev/lesson_3/level_3/task_11/RobotDemo.java, src/main/java/students/rodion_afanasjev/lesson_3/level_5/task_22/Dog.java, src/main/java/students/rodion_afanasjev/lesson_3/level_5/task_22/DogDemo.java
=> St rodion afanasjev lesson 3 level 5 task 22

src/main/java/students/kristine_paskevica/lesson_3/level_1/Robot.java, src/main/java/students/kristine_paskevica/lesson_3/level_1/RobotDemo.java
=> 3. nodarbības-level1-allTask

src/main/java/students/rodion_afanasjev/lesson_3/level_3/task_11/Robot.java, src/main/java/students/rodion_afanasjev/lesson_3/level_3/task_11/RobotDemo.java, src/main/java/students/rodion_afanasjev/lesson_3/level_7/task_28/Car.java, src/main/java/students/rodion_afanasjev/lesson_3/level_7/task_28/CarDemo.java, src/main/java/students/rodion_afanasjev/lesson_3/level_7/task_28/Paint.java, src/main/java/students/rodion_afanasjev/lesson_3/level_7/task_28/PaintDemo.java
=> Lesson-3-level-7-task-28

src/main/java/students/kristine_paskevica/lesson_3/level_2/Task7.java, src/main/java/students/kristine_paskevica/lesson_3/level_2/Task8.java, src/main/java/students/kristine_paskevica/lesson_3/level_2/Task9.java
=> lesson3-level2-allTask

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/level_1/task_1/Task1.java, src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/level_1/task_2/Task2.java
=> Lesson 2 task 1

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/level_2/Task3.java
Andrejs Kuramšins lesson 2 task 3
=> Lesson 2 task 3

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/level_2/Task_4/Task4.java
Andrejs Kuramšins lesson 2 task 4
=> St andrejs kuramsins lesson 2 task 4

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/level_2/task_6/Task6.java
Andrejs Kuramšins lesson 2 task 6
=> Andrejs Kuramšins lesson 2 task 6

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/level_2_task_5/Task5.java
Andrejs Kuramšins lesson 2 task 5
=> Andrejs Kuramšins lesson 2 task 5

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/level_2/task_8/Task8.java
Andrejs Kuramšins lesson 2 task 8
=> Andrejs Kuramšins lesson 2 task 8

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/level_3/task_9/Task9.java
Andrejs Kuramšins lesson 2 task 9
=> Andrejs Kuramšins lesson 2 task 9

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/level_3/task_10/Task10.java
Andrejs Kuramšins lesson 2 task 10
=> Andrejs Kuramšins lesson 2 task 10

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/level_3/task_11/Task11.java
Andrejs Kuramšins lesson 2 task 11
=> St andrejs kuramsins lesson 2 task 11

src/main/java/students/rodion_afanasjev/lesson_3/level_7/task_31/BankAccount.java
=> Lesson-3-level-7-task-31

src/main/java/students/rodion_afanasjev/lesson_3/level_7/task_32/Computer.java
=> Lesson-3-level-7-task-32

src/main/java/students/kristine_paskevica/lesson_3/level_7/task29/Circle.java, src/main/java/students/kristine_paskevica/lesson_3/level_7/task29/CircleDemo.java, src/main/java/students/kristine_paskevica_lesson_3/level_7/task30/Product.java, src/main/java/students/kristine_paskevica_lesson_3/level_7/task30/ProductDemo.java
Šeit pievienojās arī 30 uzdevums
=> lesson3-level7-29-un-30Task

src/main/java/students/lolita_polakova/lesson_2/level_1/task_1/TaskOne.java, src/main/java/students/lolita_polakova/lesson_2/level_1/task_2/TaskTwo.java, src/main/java/students/lolita_polakova/lesson_2/level_2/task_3/Book.java, src/main/java/students/lolita_polakova/lesson_2/level_2/task_4/Phone.java, src/main/java/students/lolita_polakova/lesson_2/level_2/task_5/BankAccount.java, src/main/java/students/lolita_polakova/lesson_2/level_2/task_6/Turtle.java, src/main/java/students/lolita_polakova/lesson_2/level_2/task_7/LoginService.java, src/main/java/students/lolita_polakova/lesson_2/level_2/task_8/Login.java, src/main/java/students/lolita_polakova/lesson_2/level_3/task_10/TaskTen.java, src/main/java/students/lolita_polakova/lesson_2/level_3/task_11/TaskEleven.java, src/main/java/students/lolita_polakova/lesson_2/level_3/task_9/TaskNine.java, src/main/java/students/lolita_polakova/lesson_2/level_5/task_15/Task15.java, src/main/java/students/lolita_polakova/lesson_2/level_5/task_18/SizeMatters.java, src/main/java/students/lolita_polakova/lesson_2/level_6/task_23/AttentionPlease.java, src/main/java/students/lolita_polakova/lesson_2/level_6/task_24/NoSleepNoFocus.java, src/main/java/students/lolita_polakova/lesson_2/level_7/task_27/Classes.java, src/main/java/students/lolita_polakova/lesson_2/level_7/task_28/SumTwoNumbers.java, src/main/java/students/lolita_polakova/lesson_2/level_7/task_29/CorrectDataTypes.java, src/main/java/students/lolita_polakova/lesson_2/level_7/task_31/Commentaries.java
=> My first (very late) attempt!

src/main/java/students/rodion_afanasjev/lesson_4/level_1/task_1/IntegerNumber.java
=> Lesson-4-level-1-task-1

src/main/java/students/rodion_afanasjev/lesson_4/level_1/task_3/Week.java, src/main/java/students/rodion_afanasjev/lesson_4/level_1/task_4/Even.java
=> Lesson-4-level-1-task-4

src/main/java/students/rodion_afanasjev/lesson_4/level_1/task_3/Week.java
=> Lesson-4-level-1-task-3

src/main/java/students/rodion_afanasjev/lesson_4/level_2/Great.java
=> Lesson-4-level-2-task-5

src/main/java/students/rodion_afanasjev/lesson_4/level_2/task_7/Equals.java
=> Lesson-4-level-2-task-7

src/main/java/students/rodion_afanasjev/lesson_4/level_2/task_6/LessDemo.java
=> Lesson-4-level-2-task-6

src/main/java/students/rodion_afanasjev/lesson_4/level_3/task_9/Increase.java
=> Lesson-4-level-3-task-9

src/main/java/students/rodion_afanasjev/lesson_4/level_3/task_8/Equals.java
=> Lesson-4-level-3-task-8

src/main/java/students/rodion_afanasjev/lesson_4/level_4/task_11/Calculator.java, src/main/java/students/rodion_afanasjev/lesson_4/level_4/task_11/CalculatorDemo.java
=> Lesson-4-level-4-task-11

src/main/java/students/rodion_afanasjev/lesson_4/level_4/task_12/Calculator.java, src/main/java/students/rodion_afanasjev/lesson_4/level_4/task_12/CalculatorDemo.java, src/main/java/students/rodion_afanasjev/lesson_4/level_4/task_12/CalculatorTest.java
=> Lesson-4-level-4-task-12

src/main/java/students/rodion_afanasjev/lesson_4/level_3/task_10/MaxNumber.java
=> Lesson-4-level-3-task-10

src/main/java/students/rodion_afanasjev/lesson_4/level_4/task_14/Calculator.java, src/main/java/students/rodion_afanasjev/lesson_4/level_4/task_14/CalculatorDemo.java, src/main/java/students/rodion_afanasjev/lesson_4/level_4/task_14/CalculatorTest.java
=> Lesson-4-level-4-task-14

src/main/java/students/rodion_afanasjev/lesson_4/level_7/task_22/FizzBuzz.java, src/main/java/students/rodion_afanasjev/lesson_4/level_7/task_22/FizzBuzzDemo.java, src/main/java/students/rodion_afanasjev/lesson_4/level_7/task_22/FizzBuzzTest.java
=> Lesson-4-level-7-task-22

src/main/java/students/rodion_afanasjev/lesson_4/level_7/task_23/LeapYear.java, src/main/java/students/rodion_afanasjev/lesson_4/level_7/task_23/LeapYearDemo.java, src/main/java/students/rodion_afanasjev/lesson_4/level_7/task_23/LeapYearTest.java
=> Lesson-4-level-7-task-23

src/main/java/students/rodion_afanasjev/lesson_4/level_7/task_24/Calculator.java, src/main/java/students/rodion_afanasjev/lesson_4/level_7/task_24/CalculatorTest.java
=> Lesson-4-level-7-task-24

src/main/java/students/rodion_afanasjev/lesson_4/level_7/task_25/LightColorDetector.java, src/main/java/students/rodion_afanasjev/lesson_4/level_7/task_25/LightColorDetectorTest.java
=> Lesson-4-level-7-task-25

src/main/java/students/rodion_afanasjev/lesson_4/level_4/task_15/Calculator.java, src/main/java/students/rodion_afanasjev/lesson_4/level_4/task_15/CalculatorDemo.java, src/main/java/students/rodion_afanasjev/lesson_4/level_4/task_15/CalculatorTest.java
=> Lesson-4-level-4-task-15

src/main/java/students/rodion_afanasjev/lesson_4/level_5/task_16/LightColorDetector.java, src/main/java/students/rodion_afanasjev/lesson_4/level_5/task_16/LightColorDetectorDemo.java, src/main/java/students/rodion_afanasjev/lesson_4/level_5/task_16/LightColorDetectorTest.java
=> Lesson-4-level-5-task-16

src/main/java/students/julija_katukova/lesson_4/level_6/task_17/Stock.java, src/main/java/students/julija_katukova/lesson_4/level_6/task_17/StockTest.java
Не уверена, что все  должен выглядеть именно так (особенно тестовый класс). Однако, все вроде бы работает нужным образом.
Логика в решении присутствует, однако, метод реализации, возможно, выбран не самый простой. 
Буду ждать комментариев. Сидела над этим заданием довольно долго.
=> Lesson4 Level6 Task17

src/main/java/students/kristine_paskevica_lesson_4/level_4/Calculator.java, src/main/java/students/kristine_paskevica_lesson_4/level_4/CalculatorDemo.java, src/main/java/students/kristine_paskevica_lesson_4/level_4/CalculatorTest.java
11,  12, 13 un 14, 15 uzdevumi, rakstu klāt komentārus koda rindiņām, man tā vieglāk mācīties
=> lesson4-level4-11-12-13-14-15Task

src/main/java/students/kristine_paskevica/lesson_4/level_6_task_17/Stock.java, src/main/java/students/kristine_paskevica/lesson_4/level_6_task_17/StockDemo.java, src/main/java/students/kristine_paskevica/lesson_4/level_6_task_17/StockTest.java
Atzīžos godīgi - šis bija grūti, daudz špikoju, bet arī tā var mācīties
=> lesson4-level6-17Task

src/main/java/students/rodion_afanasjev/lesson_4/level_6/task_17/Stock.java, src/main/java/students/rodion_afanasjev/lesson_4/level_6/task_17/StockDemo.java, src/main/java/students/rodion_afanasjev/lesson_4/level_6/task_17/StockTest.java
=> Lesson-4-level-6-task-17

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/lesson_3/level_1/task_1/Robot.java
Andrejs Kuramšins lesson 3 task 1
=> Andrejs Kuramšins lesson 3 task 1

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/lesson_3/level_1/task_6/Robot.java, src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/lesson_3/level_1/task_6/RobotDemo.java
В общем я немного не по заданию сделал, решил по экспериментировать и персонализировал каждое имя а приветствие сделал общим, но есть подозрение что в кругах программирования это делается иначе.
=> Andrejs Kuramšins lesson 3 task 6

src/main/java/students/julija_katukova/lesson_4/level_4/CalculatorTest.java
added new test to cover neative scenario
=> Lesson4 Level4

src/main/java/students/rodion_afanasjev/lesson_5/level_1/task_1/ArrayDefinition.java
=> Lesson-5-level-1-task-1

src/main/java/students/rodion_afanasjev/lesson_5/level_1/task_2/ArrayDefinition.java
=> Lesson-5-level-1-task-2

src/main/java/students/rodion_afanasjev/lesson_5/level_1/task_3/ArrayDefinition.java
=> Lesson-5-level-1-task-3

src/main/java/students/rodion_afanasjev/lesson_5/level_1/task_4/ArrayDefinition.java
=> Lesson-5-level-1-task-4

src/main/java/students/rodion_afanasjev/lesson_5/level_1/task_5/ArrayDefinition.java
=> Lesson-5-level-1-task-5

src/main/java/students/rodion_afanasjev/lesson_5/level_1/task_6/ArrayDefinition.java
=> Lesson-5-level-1-task-6

src/main/java/students/rodion_afanasjev/lesson_5/level_1/task_8/ArrayLength.java
=> Lesson-5-level-1-task-8

src/main/java/students/rodion_afanasjev/lesson_5/level_2/task_10/ArrayThreeNumbers.java
=> Lesson-5-level-2-task-10

src/main/java/students/rodion_afanasjev/lesson_5/level_1/task_7/ArrayLength.java
=> Lesson-5-level-1-task-7

src/main/java/students/rodion_afanasjev/lesson_5/level_2/task_12/ArrayRandom.java
=> Lesson-5-level-2-task-12

src/main/java/students/rodion_afanasjev/lesson_5/level_2/task_13/ArraySum.java
=> Lesson-5-level-2-task-13

src/main/java/students/rodion_afanasjev/lesson_5/level_2/task_14/ArrayAverage.java
=> Lesson-5-level-2-task-14

src/main/java/students/rodion_afanasjev/lesson_5/level_2/task_15/ArrayIncrement.java
=> Lesson-5-level-2-task-15

src/main/java/students/rodion_afanasjev/lesson_5/level_3/task_16/ForLoopDefinition1.java
=> Lesson-5-level-3-task-16

src/main/java/students/rodion_afanasjev/lesson_5/level_3/task_17/ForLoopDefinition2.java
=> Lesson-5-level-3-task-17

src/main/java/students/rodion_afanasjev/lesson_5/level_3/task_18/ForLoopDefinition3.java
=> Lesson-5-level-3-task-18

src/main/java/students/rodion_afanasjev/lesson_5/level_3/task_19/ForLoopDefinition4.java
=> Lesson-5-level-3-task-19

src/main/java/students/rodion_afanasjev/lesson_5/level_3/task_20/ForLoopDefinition5.java, src/main/java/students/rodion_afanasjev/lesson_5/level_3/task_21/ForLoopDefinition5.java, src/main/java/students/rodion_afanasjev/lesson_5/level_3/task_22/ForLoopDefinition6.java, src/main/java/students/rodion_afanasjev/lesson_5/level_3/task_23/ForLoopDefinition7.java, src/main/java/students/rodion_afanasjev/lesson_5/level_3/task_24/ForLoopDefinition8.java
=> Lesson-5-level-3-task-20-24

src/main/java/students/rodion_afanasjev/lesson_5/level_2/task_11/ArrayNumbers.java
=> Lesson-5-level-2-task-11

src/main/java/students/rodion_afanasjev/lesson_5/level_1/task_9/ArrayLength.java
=> Lesson-5-level-1-task-9

src/main/java/students/julija_katukova/lesson_5/level_5/Arrays.java, src/main/java/students/julija_katukova/lesson_5/level_5/ArraysTest.java
=> Lesson5 Level5

src/main/java/students/julija_katukova/lesson_5/level_2/task_14/Task14.java
изменили фиксированное число на ссылку длинны массива
=> Lesson5 Level2 Task14

src/main/java/students/julija_katukova/lesson_5/level_2/task_13/Task13.java
заменили сумму на более краткую форму
=> Lesson5 Level2 Task13

src/main/java/students/rodion_afanasjev/lesson_5/level_4/task_25/ArrayLength.java
=> Lesson-5-level-4-task-25

src/main/java/students/rodion_afanasjev/lesson_5/level_5/task_31/Arrays.java, src/main/java/students/rodion_afanasjev/lesson_5/level_5/task_31/ArraysTest.java
=> Lesson-5-task-31-38

resources/lesson 5/homework/level 6 - intermediate/Task_37.txt, src/main/java/students/kristine_paskevica/lesson_5/level_6/Arrays.java, src/main/java/students/kristine_paskevica/lesson_5/level_6/ArraysDemo.java, src/main/java/students/kristine_paskevica/lesson_5/level_6/ArraysTest.java
Man kaut kas nogāja greizi ar Push procesu šim 6 līmenim, divos piegājienos ar labojumiem
=> St kristine paskevica lesson 5 level 6 AllTask 34-38

src/main/java/students/julija_katukova/lesson_4/level_3/task_10/Task10.java
упростили метод нахождения максимального значения
=> Lesson4 Level3 Task10

src/main/java/students/rodion_afanasjev/lesson_6/level_2/task_7/DayOfTheWeekDetector.java, src/main/java/students/rodion_afanasjev/lesson_6/level_2/task_7/DayOfTheWeekDetectorDemo.java, src/main/java/students/rodion_afanasjev/lesson_6/level_2/task_7/DayOfTheWeekDetectorTest.java
=> Lesson-6-level-2-task-7-11

src/main/java/students/kristine_paskevica/lesson_6/level_3/ArrayService.java, src/main/java/students/kristine_paskevica/lesson_6/level_3/ArrayService13.java, src/main/java/students/kristine_paskevica/lesson_6/level_3/ArrayService14.java, src/main/java/students/kristine_paskevica/lesson_6/level_3/ArrayService15.java, src/main/java/students/kristine_paskevica/lesson_6/level_3/ArrayService16.java, src/main/java/students/kristine_paskevica/lesson_6/level_3/ArrayService17.java, src/main/java/students/kristine_paskevica/lesson_6/level_3/ArrayServiceTest.java, src/main/java/students/kristine_paskevica/lesson_6/level_3/ArrayServiceTest13.java, src/main/java/students/kristine_paskevica/lesson_6/level_3/ArrayServiceTest14.java, src/main/java/students/kristine_paskevica/lesson_6/level_3/ArrayServiceTest15.java, src/main/java/students/kristine_paskevica/lesson_6/level_3/ArrayServiceTest16.java, src/main/java/students/kristine_paskevica/lesson_6/level_3/ArrayServiceTest17.java
Varbūt dīvaini izskatās un izklausās, ka es mainīgajiem, metodēm utt. piešķiru nosaukumus latviski, bet man pēc tam ir vieglāk lasīt un analizēt kodu...
=> lesson6-level3-AllTask-12-17

src/main/java/students/rodion_afanasjev/lesson_6/level_5/task_23/TicTacToe.java, src/main/java/students/rodion_afanasjev/lesson_6/level_5/task_23/TicTacToeTest.java
=> Lesson-6-level-5-task-23

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/lesson_3/level_1/task_10/Task11.java
Andrejs Kuramšins lesson 3 task 11
=> Andrejs Kuramšins lesson 3 task 11

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/lesson_4/task_1/Task1.java
Andrejs Kuramšins lesson 4 task 1
=> Andrejs Kuramšins lesson 4 task 1

src/main/java/students/andrejs_kuramsins/lesson_2/level_0/task_0/lesson_4/task_2/Task2.java
Andrejs Kuramšins lesson 4 task 2
=> Andrejs Kuramšins lesson 4 task 2

src/main/java/students/Dmitry_Gr/lesson_6/level_2/task_7/DayOfTheWeekDetector.java, src/main/java/students/Dmitry_Gr/lesson_6/level_2/task_7/DayOfTheWeekDetectorDemo.java, src/main/java/students/Dmitry_Gr/lesson_6/level_2/task_7/DayofTheWeekDetectorTest.java
=> St dmitry gr lesson 6.level 2

src/main/java/students/julija_katukova/lesson_6/level_3/task_16/ArrayService.java, src/main/java/students/julija_katukova/lesson_6/level_3/task_16/ArrayServiceTest.java
Не уверена, что в тестах методы написаны лучшим образом, но не придумала, как по-другому протестировать void метод.
По крайне мере, все работает
=> Lesson6 Level3 Task16

src/main/java/students/julija_katukova/lesson_6/level_4/task_21/TwoDimensionalArray.java
Возможно, не самая лучшая реализация, но парилась с доступом к переменным из методов. Буду рада комментариям и советам по улучшению кода :)
=> Lesson6 Level4 Task21

src/main/java/students/julija_katukova/lesson_6/level_3/task_14/ArrayService.java
убрала лишний объект и упростила
=> Lesson6 Level3 Task14

src/main/java/students/julija_katukova/lesson_6/level_3/task_12/ArrayService.java
убрала лишний объект и упростила
=> Lesson6 Level3 Task12

src/main/java/students/julija_katukova/lesson_6/level_1/task_2/WhileDefinition2.java
=> Lesson6 Level1 Task2

src/main/java/students/julija_katukova/lesson_6/level_5/task_30/TicTacToe.java
=> Lesson6 Level6 Task30

src/main/java/students/julija_katukova/lesson_7/level_1/task_1/WordService.java, src/main/java/students/julija_katukova/lesson_7/level_1/task_1/WordServiceTest.java
Делая таск 1 уже изначально разбила код на методы и написала тесты для основного метода
=> Lesson7 Level1 Task1 & 3

src/main/java/students/julija_katukova/lesson_7/level_1/task_2/WordService.java, src/main/java/students/julija_katukova/lesson_7/level_1/task_2/WordServiceTest.java
уже в таске 1 подзадачи были разбиты на методы, поменяла модификаторы доступа с прайвит на паблик, чтобы провести тесты для этих методов. по 1 тесту на каждый метод, так как в таске 1 уже тестировался главный метод и все работало
=> Lesson7 Level1 Task2

src/main/java/students/julija_katukova/lesson_7/level_5/task_9/PowerCalculator.java, src/main/java/students/julija_katukova/lesson_7/level_5/task_9/PowerCalculatorTest.java
постаралась максимально разбить задачи на отдельные методы
тут была логика проще и легче было это реализовать, чем в таск1
буду рада услышать комментарии, где и что еще можно улучшить, чтобы код стал лучше/чище
=> Lesson7 Level5 Task9

src/main/java/students/bogdans_pavlovs/lesson_6/level_5/TicTacToe.java, src/main/java/students/bogdans_pavlovs/lesson_6/level_5/TicTacToeTest.java
=> Bogdans Pavlovs - Lesson 6 - Level 5 - Tasks 22 to 26

src/main/java/students/bogdans_pavlovs/lesson_6/level_6/Move.java, src/main/java/students/bogdans_pavlovs/lesson_6/level_6/TicTacToe.java, src/main/java/students/bogdans_pavlovs/lesson_6/level_6/TicTacToeDemo.java, src/main/java/students/bogdans_pavlovs/lesson_6/level_6/TicTacToeTest.java
Это можно было убирать? Иначе печатает поле 2 раза после каждого хода.
=> Bogdans Pavlovs - Lesson 6 - Level 6 - Tasks 27 to 31

src/main/java/students/Dmitry_Gr/lesson_6/level_6/Task_27/Move.java, src/main/java/students/Dmitry_Gr/lesson_6/level_6/Task_27/TicTacToe.java, src/main/java/students/Dmitry_Gr/lesson_6/level_6/Task_27/TicTacToePlay.java
=> St dmitry gr.lesson 6.level 6.task 27

src/main/java/students/julija_katukova/lesson_8/level_1/task_2/DefaultConstructorV2.java, src/main/java/students/julija_katukova/lesson_8/level_1/task_2/DefaultConstructorV2Demo.java
no need to create default constructor
=> Lesson8 Level1 Task2

src/main/java/students/julija_katukova/lesson_8/level_7/task_31/Book.java, src/main/java/students/julija_katukova/lesson_8/level_7/task_31/BookRepository.java, src/main/java/students/julija_katukova/lesson_8/level_7/task_31/BookRepositoryDemo.java, src/main/java/students/julija_katukova/lesson_8/level_7/task_31/Library.java, src/main/java/students/julija_katukova/lesson_8/level_7/task_31/User.java, src/main/java/students/julija_katukova/lesson_8/level_7/task_31/UserRepository.java
Finally) 
опять же, не уверена, что все так, как ожидалось, но теперь делала хоть не через двумерный массив :)
буду ждать комментариев :)
=> Lesson8 Level7 Task31

src/main/java/students/julija_katukova/lesson_9/level_3/task_16/SuperClassConstructorInvoker.java
Такое исправление подразумевалось?
=> Lesson9 Level3 Task16

src/main/java/students/julija_katukova/lesson_9/level_5/task_22/FraudDetectorByAmount.java, src/main/java/students/julija_katukova/lesson_9/level_5/task_22/FraudDetectorByCity.java, src/main/java/students/julija_katukova/lesson_9/level_5/task_22/FraudDetectorByCountry.java, src/main/java/students/julija_katukova/lesson_9/level_5/task_22/FraudDetectorByCountryAndAmount.java, src/main/java/students/julija_katukova/lesson_9/level_5/task_22/FraudDetectorByName.java, src/main/java/students/julija_katukova/lesson_9/level_5/task_22/Trader.java, src/main/java/students/julija_katukova/lesson_9/level_5/task_22/Transaction.java
Разделила FraudDetector на 5 отдельных классов, основываясь на принципе по которому они определяют мошеничество
=> Lesson9 Level5 Task22

src/main/java/students/julija_katukova/lesson_9/level_7/task_34/ConnectFour.java, src/main/java/students/julija_katukova/lesson_9/level_7/task_34/Move.java, src/main/java/students/julija_katukova/lesson_9/level_7/task_34/WinningDetector.java, src/main/java/students/julija_katukova/lesson_9/level_7/task_34/WinningRule.java, src/main/java/students/julija_katukova/lesson_9/level_7/task_34/WinningRuleForDiagonalFromLeftCorner.java, src/main/java/students/julija_katukova/lesson_9/level_7/task_34/WinningRuleForDiagonalFromRightCorner.java, src/main/java/students/julija_katukova/lesson_9/level_7/task_34/WinningRuleForHorizontals.java, src/main/java/students/julija_katukova/lesson_9/level_7/task_34/WinningRuleForVerticals.java
Постаралась разделить часть программы по классам. Что еще целесообразно улучшать?
=> Lesson9 Level7 Task34

src/main/java/students/julija_katukova/lesson_10/level_4/task_12/CelsiusConverter.java, src/main/java/students/julija_katukova/lesson_10/level_4/task_12/FahrenheitConverter.java, src/main/java/students/julija_katukova/lesson_10/level_4/task_12/FahrenheitConverterTest.java, src/main/java/students/julija_katukova/lesson_10/level_4/task_12/KelvinConverter.java, src/main/java/students/julija_katukova/lesson_10/level_4/task_12/KelvinConverterTest.java, src/main/java/students/julija_katukova/lesson_10/level_4/task_12/TemperatureConverter.java
У меня лишь один вопрос: в чем смысл класса CelsiusConverter?
=> Lesson10 Level4 Task12

src/main/java/students/julija_katukova/lesson_11/level_2/task_6/Book.java, src/main/java/students/julija_katukova/lesson_11/level_2/task_6/BookDatabase.java, src/main/java/students/julija_katukova/lesson_11/level_2/task_6/BookDatabaseImpl.java, src/main/java/students/julija_katukova/lesson_11/level_2/task_6/CountBooksTest.java, src/main/java/students/julija_katukova/lesson_11/level_2/task_6/DeleteBookByAuthorTest.java, src/main/java/students/julija_katukova/lesson_11/level_2/task_6/DeleteBookTest1.java, src/main/java/students/julija_katukova/lesson_11/level_2/task_6/DeleteBookTest2.java, src/main/java/students/julija_katukova/lesson_11/level_2/task_6/DeleteBooksByTitleTest.java, src/main/java/students/julija_katukova/lesson_11/level_2/task_6/FindBookByIdTest.java, src/main/java/students/julija_katukova/lesson_11/level_2/task_6/FindBooksByAuthorTest.java, src/main/java/students/julija_katukova/lesson_11/level_2/task_6/FindBooksByTitleTest.java, src/main/java/students/julija_katukova/lesson_11/level_2/task_6/SaveBookTest.java
Все методы, которые мы добавляли в интерфейс стоило выносить в отдельные классы?
я лишь писала реализацию самих методов в отдельных методах, делая их приватными
=> Lesson11 Level2 Task6-14

src/main/java/students/julija_katukova/lesson_11/level_6/AndSearchCriteria.java, src/main/java/students/julija_katukova/lesson_11/level_6/AuthorSearchCriteria.java, src/main/java/students/julija_katukova/lesson_11/level_6/Book.java, src/main/java/students/julija_katukova/lesson_11/level_6/BookDatabase.java, src/main/java/students/julija_katukova/lesson_11/level_6/BookDatabaseImpl.java, src/main/java/students/julija_katukova/lesson_11/level_6/BookLibrary.java, src/main/java/students/julija_katukova/lesson_11/level_6/BookLibraryApplication.java, src/main/java/students/julija_katukova/lesson_11/level_6/ContainsUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/CountAllBooksUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/DeleteBookUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/DeleteByAuthorUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/DeleteByIdUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/DeleteByTitleUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/FindByAuthorUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/FindByIdUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/FindBySearchCriteriaUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/FindByTitleUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/FindUniqueAuthorsUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/FindUniqueBooksUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/FindUniqueTitlesUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/GetAuthorsToBookMapUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/GetEachAuthorBookCountUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/OrSearchCriteria.java, src/main/java/students/julija_katukova/lesson_11/level_6/SaveBookUIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/SearchCriteria.java, src/main/java/students/julija_katukova/lesson_11/level_6/TitleSearchCriteria.java, src/main/java/students/julija_katukova/lesson_11/level_6/UIAction.java, src/main/java/students/julija_katukova/lesson_11/level_6/YearOfIssueSearchCriteria.java
=> Lesson11 Level6 Task30-38

src/main/java/students/julija_katukova/lesson_11/level_3/BookDatabaseImpl.java
Объявила счетчик как параметр класса
=> Lesson11 Level3 Task15-22

src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntity.java, src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntityRepository.java, src/main/java/students/julija_katukova/lesson_7/level_7/task_16/UserEntityRepositoryTest.java
Не было четкого представление как все должно выглядеть  - местами импровизировала
Возможно, все не совсем так должно быть, но по крайне мерее версия рабочая. Все методы тестами проверила. 
Буду ждать комментариев :)
=> Lesson7 Level7 Task16

src/main/java/students/julija_katukova/lesson_12/level_5_and_6/FieldValidationRule.java, src/main/java/students/julija_katukova/lesson_12/level_5_and_6/Product.java, src/main/java/students/julija_katukova/lesson_12/level_5_and_6/ProductDescriptionValidationRule.java, src/main/java/students/julija_katukova/lesson_12/level_5_and_6/ProductPriceValidationRule.java, src/main/java/students/julija_katukova/lesson_12/level_5_and_6/ProductTitleValidationRule.java, src/main/java/students/julija_katukova/lesson_12/level_5_and_6/ProductValidator.java, src/main/java/students/julija_katukova/lesson_12/level_5_and_6/ProductValidatorImpl.java, src/main/java/students/julija_katukova/lesson_12/level_5_and_6/ProductValidatorImplTest.java, src/main/java/students/julija_katukova/lesson_12/level_5_and_6/ValidationException.java
Тесты не проходят, не могу понять почему (
=> Lesson12 Level5 and Level6 Task27-46
